/**
 * !!! This file is generated by the gulp task build-config !!!
 */
/// <reference path="../../../../typings/tsd.d.ts" />

module c3.core.constants {
  'use strict';

  export interface IAppConfig {
    ENVIRONMENT: string;
    BASE_URL: string;
    LANGUAGE: string;
  }

  angular
    .module(ID.AppConfig, [])
    .constant(ID.AppConfig, {
      ENVIRONMENT: 'development',
      BASE_URL:    'http://localhost:1337/api/',
      LANGUAGE:    'en'
    });

}
