/**
 * !!! This file is generated by the gulp task build-config !!!
 */
/// <reference path="../../../../typings/tsd.d.ts" />

module c3.core.constants {
  'use strict';

  export interface IAppConfig {
    ENVIRONMENT: string;
    BASE_URL: string;
    LANGUAGE: string;
    CLIENT_ID: string;
    CLIENT_SECRET: string;
  }

  angular
    .module(ID.AppConfig, [])
    .constant(ID.AppConfig, {
      ENVIRONMENT: '<%= environment %>',
      BASE_URL: '<%= baseUrl %>',
      LANGUAGE: '<%= language %>',
      CLIENT_ID: '<%= client_id %>',
      CLIENT_SECRET: '<%= client_secret %>'
    });

}
